### ISSUE TITLE
How does safe-exit compare to pyterminate?

### ISSUE THREAD

**Issue by Emasoft** [ZhangJianAo/safe-exit#1]
How does safe-exit compare to [pyterminate](https://github.com/jeremyephron/pyterminate)?

**Comment by ZhangJianAo** [comment]
Looks like pyterminate has similar goals of safe-exit. however, I noticed pyterminate lacks some feature that safe-exit have.

- safe-exit support Windows platform, The Windows platform has different mechanisms to catch process exit events.
- safe-exit has functions to help safe kill other processes, let them have the opportunity to run clean-up code.
